### ISSUE TITLE
Node exporter fails on ec2 builds with ""No file was found when using first_found"

### ISSUE THREAD

**Issue by denmat** [cloudalchemy/ansible-node-exporter#115]
https://github.com/cloudalchemy/ansible-node-exporter/pull/114 has renamed `redhat.yml` to `redhat-7.yml`.

This has broken Amazon ec2 installs with

> {"msg": "No file was found when using first_found. Use the 'skip: true' option to allow this task to be skipped if no files are found"}

Amazon returns `"ansible_os_family": "RedHat",`  and here is where I assume we used to match it:
https://github.com/cloudalchemy/ansible-node-exporter/blob/0a594311180fa8570145872f86ffba540889c974/tasks/main.yml#L11

Just needs a symlink to the old `redhat.yml` from `redhat-7.yml` I reckon (or 8 - I'm not sure).

**Comment by paulfantom** [comment]
What is the operating system being used? `Amazon EC2` is more or less a virtualization platform and not an Operating System.

**Comment by paulfantom** [comment]
Also it would be nice to have values of:
```
ansible_distribution
ansible_distribution_file_variety
ansible_distribution_version
ansible_distribution_major_version
```

**Comment by denmat** [comment]
```
        "ansible_distribution": "Amazon",
        "ansible_distribution_file_parsed": true,
        "ansible_distribution_file_path": "/etc/system-release",
        "ansible_distribution_file_variety": "Amazon",
        "ansible_distribution_major_version": "2",
        "ansible_distribution_release": "NA",
        "ansible_distribution_version": "2",
```
It's a RedHat based OS - xen virtualization under the hood.

**Comment by aharden** [comment]
@paulfantom Thanks for this module. I'd previously privately updated an earlier version to work with Amazon Linux by adding support for an upstart-based service.  Now that Amazon Linux 2 is identified differently by Ansible, I'm going to work on wedging support for it into the module - it should just mean copying the RH7 settings.  Regarding Amazon Linux 2 testing: with this release, Amazon is releasing VM images for several platforms so that it can be run outside of EC2: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/amazon-linux-2-virtual-machine.html.  Also, official "amazonlinux" Docker Hub images are available for both Amazon Linux and Amazon Linux 2: https://hub.docker.com/_/amazonlinux.

**Comment by aharden** [comment]
Confirmed that on Amazon Linux 2, copying `vars/redhat-7.yml` to `vars/amazon.yml` resulted in a successful service install.

**Comment by paulfantom** [comment]
I believe this is fixed in #132. @aharden if you can, please confirm.

**Comment by aharden** [comment]
@paulfantom Confirmed on Amazon Linux 2 x86.  Thanks!

**Comment by chrisrohr** [comment]
Thank you for this role.  Do you have an estimated time you might cut another release that will include #132

**Comment by paulfantom** [comment]
> Do you have an estimated time you might cut another release

Yes, today :smile:

**Comment by chrisrohr** [comment]
👍 Thank you!
