### ISSUE TITLE
Hardcode node-exporter username and group

### ISSUE THREAD

**Issue by escalate** [cloudalchemy/ansible-node-exporter#139]
Hello

In all cloudalchemy roles username and group are hard coded. 
In this role username and group are freely definable.
Is there a reason for this?
I think it should be the same style in all roles for convenient reasons.
Either username and group are hard coded or freely definable.
Do we have an opinion on this?

Greetings

**Comment by paulfantom** [comment]
I agree, this should be uniform. However this was introduced due to some features in node_exporter needing `root` permissions (more in https://github.com/cloudalchemy/ansible-node-exporter/pull/74) and as such it is necessary only in this role and not in others.

The ultimate goal for all cloudalchemy roles is to get rid of user management and use systemd dynamic users whenever possible (more on dynamic users at http://0pointer.net/blog/dynamic-users-with-systemd.html).

**Comment by escalate** [comment]
Thank you for the explanation. I will close this issue.

**Comment by paulfantom** [comment]
@SuperQ what is the current status of using `root` user for node_exporter? Is this still necessary for some collectors (mostly systemd one)? Were there some changes and we can now (or in near future) disable it here and force usage of unprivileged user?

I am asking because I found this PR: https://github.com/prometheus/node_exporter/pull/1587

**Comment by SuperQ** [comment]
There was only one sub-feature of the systemd collector that needed root. We have recently made that a hidden flag.

The intention of the node_exporter is that it doesn't need privileges.

**Comment by paulfantom** [comment]
Let's reopen this and remove support for changing user (and especially references to `root` user).

I think leaving `*_system_user` and `*_system_group` as internals variables living in `vars/main.yml` should be ok until all supported OSes use systemd 235 (version which provides dynamic users feature).
