### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by abh** [cloudalchemy/ansible-node-exporter#258]
it'd be nice to have a new release cut to fix #233 (and the various duplicates).

**Comment by abroyere-preligens** [comment]
Any news on this topic ? It seems pretty important as the role is unusable if pulled from galaxy

**Comment by peschmae** [comment]
@SuperQ Is that something you could look into? It would be great to have a working version again in ansible galaxy

**Comment by jonesbusy** [comment]
Same issue here, looking for a new release

**Comment by rcousens** [comment]
Also using a commit hash to circumvent various issues atm, would love a release!

**Comment by wakaru44** [comment]
I just lost my sunday to troubleshoot an issue with this 😓 , only to end up finding about this bug.

As an idea, maybe it would it be posible to save  others some time by updating the README to mention this little issue and the tip to fix a commit or the master branch.

**Comment by rockhowse** [comment]
I am going to chime in here with about 0.5 day spent testing this using `molecule`, applying it only to find the second attempt at running this role failing with the issue that has been fixed. 

If there is any way for us to assist in getting an official release with the fix https://github.com/cloudalchemy/ansible-node-exporter/pull/233 included that would allow folks to use galaxy instead of relying on a commit hash on master.

**Comment by zhan9san** [comment]
Here is a non-official forked

You can have a try.

https://github.com/devops37/ansible-node-exporter

**Comment by antonr-p2p** [comment]
You can find fixed version in https://github.com/prometheus-community/ansible/tree/main/roles/node_exporter

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
