### ISSUE TITLE
Role doesn't work with Ansible 7.0.0 

### ISSUE THREAD

**Issue by gygitlab** [cloudalchemy/ansible-node-exporter#276]
Hey. Looks like the role doesn't support [Ansible 7.0.0](https://github.com/ansible-community/ansible-build-data/blob/main/7/CHANGELOG-v7.rst#ansible-core-5) due to the following `shell` deprecation:

```
TASK [cloudalchemy.node_exporter : Gather currently installed node_exporter version (if any)] **********************************************************************************************
fatal: [node-1]: FAILED! => changed=false
  msg: 'Unsupported parameters for (ansible.legacy.command) module: warn. Supported parameters include: _raw_params, executable, strip_empty_ends, stdin_add_newline, creates, chdir, removes, stdin, _uses_shell, argv.'
```

**Comment by yqlbu** [comment]
I am underging the same issue. Any solutions available?

**Comment by nono-lqdn** [comment]
You can just remove the part with 

```
  args:
     warn: false
 ```

and replace it with a `ignore_errors : false `

This is because we are, in the task with the name "[ansible-node-exporter : Gather currently installed node_exporter version (if any)] ", we are trying to execute a shell command that might not exist. Thus we need to ignore errors.

**Comment by nono-lqdn** [comment]
I've pushed the fix I've applied locally.

**Comment by vladget** [comment]
+1

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
